SS-213 RStudio helm chart for app deployment
ScilifelabDataCentre/stackn pull request #28
Opened 2023-01-10 08:33 UTC by alfredeen

## Status

- [ ] Ready
- [ ] Draft
- [ ] Hold

## Description

A helm chart for RStudio sourced from the rocker/rstudio image. The helm chart is based on a similar chart for VSCode and therefore shares many of the same settings. The home catalogue (working directory) for user files in the RStudio app becomes /home/rstudio.

[Jira task](https://scilifelab.atlassian.net/browse/SS-213)

## Types of changes

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [x] New feature
- [ ] Documentation update

2023-01-10 10:08 UTC, talavis requested changes
Some comments to start off, might add more later.

Also: do _not_ forget to create a `NetworkPolicy` as well to avoid exposing the internal network to external users.

2023-01-10 10:08 UTC, talavis commented on components/studio/charts/apps/rstudio/chart/templates/deployment.yaml
> +      containers:
Where is the `securityContext`?

You need to make sure that the pod has no elevated permissions, do not run as root etc. The best is also to make the whole container read-only, adding `emptyDir`s where you need to be able to write (you should anyway have `emptyDir`s for those folders for performance reasons, even if they are not read-only). The default `securityContext` I use for pod-level is:
```
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 10500
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
            runAsGroup: 10500
```

2023-01-10 10:08 UTC, talavis commented on components/studio/charts/apps/rstudio/chart/templates/deployment.yaml
> +          - containerPort: 8787
Add a name here (`name: backend` or similar) and you can refer to that name in the service instead of messing around with remembering numbers

2023-01-10 10:08 UTC, talavis commented on components/studio/charts/apps/rstudio/chart/templates/deployment.yaml
> +      - name: rstudio
If possible, you want to set up a `readinessProbe` as well, the easiest is probably to just check if the port gives any response:
```
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 8787  # or backend, if you follow my name suggestion in a different comment
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
```

2023-01-10 10:10 UTC, talavis commented on components/studio/charts/apps/rstudio/chart/templates/deployment.yaml
> +          - containerPort: 8787
Also, you probably want to use `.Values.service.targetport` or similar here, as the value otherwise makes no sense.

2023-01-10 11:55 UTC, talavis commented
See https://scilifelab.atlassian.net/wiki/spaces/DC/pages/2342912178/Guidelines+when+creating+deployments for a bit more information about some of my comments.

2023-01-11 13:23 UTC, alfredeen commented
Improvements such as those suggested will be worked on as part of a large group effort that will entail deciding on standard use of the helm chart templates and their configuration. These will be added as separate backlog items to be worked on over the near future.

2023-08-14 11:17 UTC, closed without merging