Merged new code from scaleoutsystems/stackn/release/v0.7.0
ScilifelabDataCentre/stackn pull request #50
Opened 2023-08-18 13:04 UTC by sandstromviktor

## Status

- [ ] Ready
- [X] Draft
- [ ] Hold

## Description
Merged code from `scaleoutsystems/stackn/release/v0.7.0`

## Types of changes

What types of changes does your code introduce to STACKn?

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [X] New feature
- [ ] Documentation update

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [ ] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [ ] I have read the [CONTRIBUTING](https://github.com/scaleoutsystems/stackn/blob/master/CONTRIBUTING.md) doc
- [ ] I have included, reviewed and executed tests (unit and end2end) to complement my changes
- [ ] I have updated the related documentation (if necessary) 
- [ ] I have updated the release notes (docs/releasenotes.md)
- [] I have added a reviewer for this pull request
- [X] I have added myself as an author for this pull request

2023-08-19 11:26 UTC, churnikov reviewed
Jeez, how many files

Gonna be honest, with docscrings I used chatgpt, but I read through code and I was satisfied with the result.

I tried to look through as much as possible, but there is still some files left to look at.

2023-08-19 11:26 UTC, churnikov commented on apps/models.py
>      def user_can_create(self, user, project, app_slug):
```suggestion
    def user_can_create(
    self, 
    user: User, 
    project: Project, 
    app_slug: str
    ) -> bool:
    """
    Determine if a user can create an app instance based on various conditions.

    :param user: The user for whom the permission is being checked.
    :param project: The project in which the app instance is to be created.
    :param app_slug: The slug of the app for which the instance is to be created.
    :return: A boolean indicating whether the user can create the app instance.

    .. note::
        - The method checks the app's ``user_can_create`` attribute.
        - It also considers the number of app instances already created against the allowed limit.
        - If the user has the "apps.add_appinstance" permission, they can always create the app instance, regardless of the limit.
    """
```

2023-08-19 11:26 UTC, churnikov commented on apps/tests/test_app_instance_manager.py
> +from ..models import AppInstance, Apps
```suggestion
from apps.models import AppInstance, Apps
```

2023-08-19 11:26 UTC, churnikov commented on apps/tests/test_app_settings_view.py
> +from ..models import AppCategories, AppInstance, Apps
```suggestion
from apps.models import AppCategories, AppInstance, Apps
```

2023-08-19 11:26 UTC, churnikov commented on projects/management/commands/removedeletedprojects.py
> +            except Exception:
```suggestion
            # TODO: Make exception explicit
            except Exception:
```

2023-08-19 11:26 UTC, churnikov commented on projects/models.py
> +    except Exception:
```suggestion
    # TODO: Make exception explicit
    except Exception:
```

2023-08-22 09:32 UTC, alfredeen commented on apps/admin.py
> +    list_display = (
It seems like this change undoes the formatting of black. Have you run the black formatter on the fetched code?

2023-08-22 10:40 UTC, alfredeen requested changes
Please run tools isort and black for formatting before merging. isort should modify 5 files and black 22 files. Also flake8 detects 2 problems.

2023-08-23 11:42 UTC, sandstromviktor reviewed
I've run Black, isort and flake.

2023-08-23 11:48 UTC, merged

2023-08-23 11:53 UTC, alfredeen commented
> I've run Black, isort and flake.

Thank you!